<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * PRD v2 §3.17 / §5.1 — the traceability spine of the whole system
 * (sdd.md §5 flags this exact column: "unique, indexed string column —
 * get the index right from migration #1"). Pattern:
 * `{OrderNo}-{Style}-{Color}-{CutDate:YYMMDD}-{BundleSeq}-{PieceSeq}`,
 * e.g. `0000012-A1-BLK-260816-003-014`. Generated by
 * App/Services/CuttingService when a Cut Ticket is finalized — never
 * client-supplied.
 *
 * `order_id` is denormalized off bundle->cut_ticket->order specifically
 * so "find every piece for order X" (PRD v2 §3.17/report lookup by
 * serial) doesn't need a 3-table join on every traceability query.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('piece_serials', function (Blueprint $table) {
            $table->id();
            $table->foreignId('bundle_id')->constrained('bundles')->restrictOnDelete();
            $table->foreignId('order_id')->constrained('orders')->restrictOnDelete();
            $table->string('serial')->unique();
            $table->enum('status', [
                'cut', 'in_sewing', 'sewn', 'qc_passed', 'qc_rejected', 'finished_goods', 'shipped',
            ])->default('cut')->index();
            $table->string('qc_reject_reason')->nullable();
            $table->foreignId('qc_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('qc_at')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('piece_serials');
    }
};
