<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Passport Guard
    |--------------------------------------------------------------------------
    |
    | sdd.md §4: the admin SPA authenticates via the Password Grant against
    | this guard. config/auth.php's "api" guard uses the "passport" driver,
    | so `auth:api` middleware on every module route resolves through here.
    |
    */

    'guard' => 'api',

    'middleware' => [],

    /*
    |--------------------------------------------------------------------------
    | Encryption Keys
    |--------------------------------------------------------------------------
    |
    | Generated by `php artisan passport:keys` (see backend/SETUP.md). Keys
    | are stored as local files under storage/ by default — never commit
    | them (failed_doc.md §8: no secrets/keys in git).
    |
    */

    'private_key' => env('PASSPORT_PRIVATE_KEY'),

    'public_key' => env('PASSPORT_PUBLIC_KEY'),

    /*
    |--------------------------------------------------------------------------
    | Passport Database Connection
    |--------------------------------------------------------------------------
    */

    'connection' => env('PASSPORT_CONNECTION'),

];
